### ISSUE TITLE
[Untranslated]: Battle - Missing subtitles

### ISSUE THREAD

**Issue by orbea** [lifebottle/Tales-of-Destiny-DC#1730]
version: `v0.0.236`

I'm noticing there are missing subtitles for a lot of spoken dialogue during battles, is reporting these issues within scope of the issue tracker?

For example it seems many if not all of the sacred artes are missing subtitles except for Stahn's, this includes at least `Trickster` (Rutee), `Tres Bien Hip` (Kongman), `Cleansing Inferno`, `Infernal Suffering` (Leon) and `Gaia's Fury` (Mary).

Additionally at least  one of Kongman's ending dialogues is missing subtitles.
![ToD_Battle_Kongman_subs](https://user-images.githubusercontent.com/4204285/184005431-8138a3d8-960a-47d4-929b-d6f264d87c9f.png)

**Comment by JulianoW** [comment]
Hi.

These are still a WIP. Blast Calibers and Boss Quotes are next, and may be the final extent of what gets subbed.

If you're able to provide a clip of the missing Kongman victory quote, or at least a transcribed version of what he says (if you speak Japanese), that would be helpful. Thanks!

**Comment by ichronox** [comment]
I think Kong has a couple of missing quotes, have run into some of them not very rarely. I think a short session on easy difficulty and low lvl enemies while recording should bring them out after a while.

**Comment by JulianoW** [comment]
I tried to trigger this for a good 10 minutes with no luck.

Note this feature isn't available yet, but should be within the next week or so if all goes well. Posting this now so I don't forget to do it later.

I added a new debug feature into battle subs that will be available next release. You'll need to use Cheat Engine to enable it. Do a string search for "DEBUG=", right click browse memory region, and change the 00 after DEBUG= to 01, as seen in the screenshot below. Sorry it's not straightforward to enable. (You could try doing it from the emulator's debug memory view thing, address is 4b51346, but is possible it may change, but CE should always work.

![image](https://github.com/lifebottle/Tales-of-Destiny-DC/assets/6155506/8e7fae09-d1df-4213-bb7c-d75e23614634)

Enabling this will add a debug string at the top of the screen that shows the last 5 voice ids that aren't subbed. If you could grab a screenshot when you trigger the quote, that should help me pinpoint what needs to be added.

Thanks!

**Comment by orbea** [comment]
> I tried to trigger this for a good 10 minutes with no luck.

I have also tried to reproduce this without luck, perhaps its only present on the pirate ship where Kongman is first usable?

**Comment by furiousg4m3r** [comment]
All Battle subs were not imported yet. All have been completed as of the most recent patch. I'm going to close this issue. Submit a new one if you find further issues at this point.
