### ISSUE TITLE
[Proofreading]: Synopsis - Harmentz Inn Save Point

### ISSUE THREAD

**Issue by pnvnd** [lifebottle/Tales-of-Destiny-DC#1750]
# Please describe correction needed:
Synopsis - Harmentz Inn Save Point may need proofreading on line 3 (repeated "**a**")
```
Rutee is able to pawn off the
treasure they obtained in the temple
to Walt for **a a** tidy sum.
Walt then throws a grand reception
that evening for Stahn and company.
but the following morning they somehow
find themselves surrounded by enemies.
Now they must escape!
```

# Please paste or attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/65086728/196227930-16899642-d05a-4294-9940-1d78af6394e9.png)

**Comment by furiousg4m3r** [comment]
I removed the extra "a" and re-linebroke the passage. It will get inserted at some point. Thanks for reporting.
