### ISSUE TITLE
[Bug]: after finish the game ,and some error about the staff-list font

### ISSUE THREAD

**Issue by JWleo** [lifebottle/Tales-of-Destiny-DC#1763]
Please describe the problem: 
**Some error about the staff-list font after finish the final boss**

Please paste or attach a screenshot of the issue.
![IMG_8229 HEIC](https://github.com/lifebottle/Tales-of-Destiny-DC/assets/32316654/494b1dd6-90d5-4c32-ab92-6f0e764de463)
![IMG_8230 HEIC](https://github.com/lifebottle/Tales-of-Destiny-DC/assets/32316654/76b20ddb-3c6b-48a7-98b5-0cce737be3e9)

**Comment by furiousg4m3r** [comment]
This is expected as we removed some of the JP text for space. This is on our list for the 1.0 release, thanks for the report.
