### ISSUE TITLE
[Proofreading] Various

### ISSUE THREAD

**Issue by ADeliciousBerryPie** [lifebottle/Tales-of-Destiny-DC#1785]
Sorry, I stockpiled a few of them. Some of them may have already been fixed, as I'm still using v0.0.242. I'm sorry, if so. Thank you for your hard work.

A double space is present in a sub-event.
```
That's our Mary. Always
asking  what no one else
can bring themselves to.
``` 
![image1](https://github.com/lifebottle/Tales-of-Destiny-DC/assets/69227996/49dc1f0d-9ed6-4e36-8878-1c108e6d54f5)

Typo on "Berselium" in the trash mountain in Junkland.
```
We'll have to take our search
for the Berslium elsewhere.
```
![image2](https://github.com/lifebottle/Tales-of-Destiny-DC/assets/69227996/3672a787-2f0f-44f3-8597-1fe65947df5c)

Grammar issues in a sub-event.
```
Recently, the public have been treating
those of us who live in the mansion with
harshly, as though we were synonymous
with the Oberon Corporation.
```
![image3](https://github.com/lifebottle/Tales-of-Destiny-DC/assets/69227996/b1660bb6-fc4d-4c88-b35e-762ca2e552bc)

Using "desert" instead of "dessert" in a sub-event. I'm not sure if that's intentional or not since the style of speech gives the feeling the writer of the diary might canonically use the wrong words. Nitpicking, but also punctuation is meant to go outside of quotations or brackets unless it applies to the word/sentence/quote within those quotations or brackets. In this case, the pudding is not named "Pudding!" with an exclamation point; the writer is the one exclaiming, so the exclamation point should go outside. There might be other examples of this within the translated script that I was blind to, since this punctuation rule is so frequently broken.
```
Can you believe it? He made me
a desert he called "Pudding!" Eee!
```
![image4](https://github.com/lifebottle/Tales-of-Destiny-DC/assets/69227996/b4ec215e-e0b0-43b4-9d10-d9b863428f13)

There's also possibly a misnamed floor of the trash mountain in Junkland. On the first floor, there are two exits to "B1F", but they're clearly two different areas, as one is a dead end and the other continues down. I don't know if they were originally marked this way in Japanese or not. It may be a good idea to differentiate between them if possible anyway, as I spent about an hour running around lost as to where to go because I thought it was just non-euclidian dungeon design that looped in on itself.

**Comment by furiousg4m3r** [comment]
A lot has been changed since your version. Please download the newest patch and check things out.
